name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip3 install --upgrade pip3
        pip3 install pylint black progressbar pysqlite3
         
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '**/*.py')
        black $(git ls-files '**/*.py')